// Roteiros de objeção destilados das intervenções do Gusthavo e do Pedro em conversas que viraram
// venda (compradores desde 01/07/2026). Gerados por destilar-intervencoes.ts e revisados pelo
// Gusthavo em 04/10/2026: aprovados ou ajustados (sem cupom, desconto, link ou fato datado).
// Ingeridos no RAG por ingerir-intervencoes.ts. Texto anonimizado: o repositório é público.

export interface RoteiroIntervencao {
  objecao: string;
  titulo: string;
  /** Frases como o lead fala: é daqui que sai o embedding da busca. */
  gatilhos: string;
  conteudo: string;
}

export const ROTEIROS_INTERVENCAO: RoteiroIntervencao[] = [
  {
    "objecao": "forma_pagamento",
    "titulo": "Formas de pagamento: quer saber opções (cartão, pix, boleto)",
    "gatilhos": "Quais as formas de pagamento? / É no cartão ou pode ser boleto? / Dá pra pagar com cartão de crédito? / Esses 12x pode ser em boleto ou apenas cartão? / E ele tem parcelamento em pix ou boleto? / Preciso saber como funciona com vocês as formas de pagamento / Como seria no boleto? / Tem opção de boleto?",
    "conteudo": "Explique as formas de pagamento de forma objetiva e puxe a preferência do lead. Cartão parcela em até 12x; boleto ou PIX parcelado também vai em até 12x, uma parcela por mês, sem depender do limite do cartão. Deixe claro que é compra única, não assinatura: o parcelamento é só a forma de pagar. O link do parcelado só vai depois que o lead confirmar que entendeu como funciona.\nExemplos de mensagens:\n\"Dá sim. Você prefere pagar no cartão ou no boleto/PIX parcelado?\"\n\"No boleto ou no PIX parcelado vai em até 12x, uma parcela por mês, sem precisar de limite no cartão. Ficou claro como funciona?\"\n\"Fechando, me avisa aqui quando finalizar.\"\nO que NÃO fazer: não inventar desconto ou condição especial; não falar em entrada; não entrar em detalhe de preço aqui."
  },
  {
    "objecao": "forma_pagamento",
    "titulo": "Limite/parcelamento: cartão não passa, estoura limite ou quer dividir (2 cartões/misto)",
    "gatilhos": "Excedeu o limite do cartão / Tá passando do limite ainda / o limite não dá total / Tenho a possibilidade de pagar metade a vista e metade em 6x? / Pode usar duas formas de pagamento diferentes? / Boleto de 2.000 e o restante no cartão / teria como dividir em dois cartões? / deixa eu só resolver uma questão de limite",
    "conteudo": "Diagnostique rápido se o único impeditivo é o limite do cartão. A primeira saída é o boleto ou PIX parcelado: até 12x, uma parcela por mês, sem depender do limite. Você não gera links separados nem divide o valor entre cartões; se mesmo com o parcelado o lead precisar dividir em dois cartões ou misturar formas, use Escalar_humano para a equipe montar o pagamento.\nExemplos de mensagens:\n\"O problema é só o limite do cartão?\"\n\"Então o boleto ou PIX parcelado resolve: vai em até 12x, uma parcela por mês, sem usar o limite. Quer que eu te explique como fica?\"\n\"Pra dividir em dois cartões eu passo pra equipe montar certinho pra você.\"\nO que NÃO fazer: não prometer condição especial; não culpar o lead; não empurrar só cartão quando ele já disse que não tem limite; não dizer que vai gerar dois links."
  },
  {
    "objecao": "forma_pagamento",
    "titulo": "Recorrência/boletos mensais e data: quer débito recorrente, pagar depois ou entender vencimento/erro",
    "gatilhos": "Faz cartao de credito recorrente? / Tem algum plano com cobrança recorrente? / uma forma de débito recorrente? / eu só consigo fazer dia 06 porque o cartão vira / Eu só preciso esperar até amanhã para receber o meu salário / Pelo horário não consigo pagar por pix, amanhã faço / No caso todo mês eu faria o pagamento? / está dando erro com o pagamento",
    "conteudo": "Quando o lead pede cobrança recorrente, esclareça que a mentoria é compra única e que o parcelamento é só a forma de pagar: no cartão em até 12x, ou no boleto/PIX parcelado em até 12x, uma parcela por mês. Se o lead só consegue pagar amanhã ou num dia X, combine a data e peça para avisar quando pagar. Se der erro ou recusa no pagamento, oriente a falar com o banco e ofereça reenviar o link para uma nova tentativa.\nExemplos de mensagens:\n\"A mentoria é compra única, não é assinatura. Dá pra parcelar e ir pagando mês a mês. Qual forma fica melhor pra você?\"\n\"Se você só consegue pagar dia 06, sem problema. Posso te chamar nesse dia?\"\n\"Deu erro no cartão? Às vezes o banco bloqueia compra online. Vê com eles e me fala que eu te reenvio o link.\"\nO que NÃO fazer: não oferecer débito recorrente; não inventar prazo ou escassez; não deixar o lead sem próximo passo (sempre combinar data e retorno)."
  },
  {
    "objecao": "preco",
    "titulo": "Preço: quer saber valores e escolher plano",
    "gatilhos": "Qual o investimento da mentoria? / Quanto custa a mentoria? / Me passa o valor total / só me passa a relação de valores / E quais são os outros pacotes? / E a parte mais importante de todas rsrs e qual o plano? Tem apenas anual, tem semestral? / Qual custo semestral e anual? / Quanto vou pagar?",
    "conteudo": "O lead pediu o valor: siga o pitch de preço do roteiro (o plano recomendado e o Semestral como alternativa), sem listar todos os planos. Antes do número, se ainda não fez, descubra se ele já tem material, porque isso define qual plano você recomenda. Se o lead só quer o valor, não entre em justificativa longa nem compare com salário. Se perguntar das formas de pagamento, diga que tem cartão e boleto/PIX parcelado, e que no boleto pode haver um pequeno acréscimo por taxa.\nExemplos de mensagens:\n\"Te passo sim. Só me confirma uma coisa antes: você já tem material de estudo ou precisaria dele junto?\"\n\"Você já tem Gran ou Estratégia? Assim eu te passo a opção certa.\"\nO que NÃO fazer: não oferecer \"3, 6 ou 12 meses\" de cara; não prometer bônus ou condição do dia; não falar de cupom ou desconto; não responder com frase vaga sem dar o número a quem pediu duas vezes."
  },
  {
    "objecao": "preco",
    "titulo": "Preço: achou caro/pesado e não consegue agora",
    "gatilhos": "No momento, está um pouco pesado pra mim / Ainda tô na dúvida se vale um investimento tão alto / Nossa fiquei triste agora / Nesse momento eu não tenho como nesse valor / To com pouco dinheiro hahahahahahahaah / Não baixa mais nenhum pouquinho / não consigo me comprometer com o valor do anual / vou trabalhar mais pra conseguir pagar",
    "conteudo": "Você deve acolher a objeção e diagnosticar o que exatamente pesa (parcela vs total) e o contexto (já tem material? edital próximo?). Em seguida, ofereça um caminho de entrada mais leve (plano menor ou sem material) mantendo o posicionamento de valor (método, acompanhamento, organização, plataforma). Antes de descer de plano, ofereça o boleto/PIX parcelado; se descer, é Semestral antes de Trimestral. Se fizer sentido, use a garantia de 7 dias como redução de risco. Feche com uma pergunta de decisão simples (qual plano faz sentido / quer começar por esse caminho?).\n\nMensagens exemplo:\n\"Entendo. O que pesa mais pra você: o valor total ou a parcela?\"\n\"Você já tem material de estudos? Se já tiver, dá pra ir na mentoria sem material e ficar mais leve pra começar.\"\n\"Se você quiser, pode entrar e testar por 7 dias; se não fizer sentido pra você, você pede o cancelamento. Quer tentar pra ver se encaixa?\"\n\nNão fazer: pressionar com escassez inventada (vagas acabando/expira em X minutos) nem prometer aprovação; evite discutir desconto/cupom e foque em ajuste de plano e forma de pagamento."
  },
  {
    "objecao": "preco",
    "titulo": "Preço: divergência/condição anterior (valor diferente, juros, boleto, contrato antigo)",
    "gatilhos": "Esta correto? Achei que eram 12x de 197 / Esse plano ta diferente do q vc me passou / o valor no link é diferente do que foi informado, porque? / Quando eu dividi teve juros / Mas o valor ta acima do que foi dito / Não era 12x 167,00 ? / Será que a gente não consegue chegar pelo menos no valor do último contrato? / Esse desconto não entrou no link, correto?",
    "conteudo": "Trate como dúvida técnica, não como negociação. Confirme o que o lead está vendo (forma de pagamento e plano) e explique a causa da diferença: cartão versus boleto/PIX parcelado (no boleto costuma aparecer um pequeno acréscimo por taxa de emissão), juros do parcelamento do cartão, ou link de outra modalidade. Se o lead comparar com um valor antigo ou uma condição que recebeu antes, não negocie: diga que o valor do link é o atual e, se ele insistir na condição anterior, use Escalar_humano.\nExemplos de mensagens:\n\"Deixa eu entender: você está tentando no cartão ou no boleto/PIX parcelado? No boleto costuma aparecer um pequeno acréscimo por taxa de emissão.\"\n\"Esse juros que aparece é do parcelamento do cartão, não é um acréscimo nosso.\"\n\"Esse valor é o de hoje. Sobre a condição que você recebeu antes, vou pedir pra equipe ver com você.\"\nO que NÃO fazer: não inventar promoção relâmpago ou escassez; não discutir cupom ou desconto; não dizer valor da taxa; não deixar o lead confuso com muitos números."
  },
  {
    "objecao": "adiamento",
    "titulo": "Adiamento por correria/sem tempo agora (quer fazer mais tarde hoje)",
    "gatilhos": "tô no serviço / agora estou no trabalho / acabei de chegar / cheguei agora / não tô em casa pra fazer isso agora / quando eu chegar faço / tô indo pra universidade agora / tô no centro cirúrgico agora",
    "conteudo": "Instrução: acolha a correria sem pressionar, combine um horário específico para retomar e facilite o próximo passo (enviar/gerar link quando o lead estiver pronto). Cheque se o link ainda está válido e ofereça gerar outro se tiver expirado. Peça para avisar assim que finalizar.\n\nMensagens exemplo: \"Sem problemas. Que horas hoje fica melhor pra eu te mandar/reenviar pra você finalizar com calma?\" \"Quando tiver uma pausa, tenta por ali e me avisa se travar em alguma parte que eu te ajudo.\" \"Assim que concluir, me chama aqui.\"\n\nO que NÃO fazer: não inventar escassez; não insistir com várias mensagens seguidas sem combinar horário; não prometer nada além de ajudar no passo a passo."
  },
  {
    "objecao": "adiamento",
    "titulo": "Adiamento por data específica (salário/fatura/banco/semana que vem) e pedido de follow-up",
    "gatilhos": "só preciso esperar até amanhã / recebo no quinto dia útil / só consigo dia 06 / só lá para o dia 5 / só posso na próxima semana / consigo finalizar apenas na quinta / na sexta farei o pagamento / quarta feira / amanhã de manhã",
    "conteudo": "Instrução: confirme a data que o lead consegue, peça permissão para chamar no dia e horário combinados e mantenha o compromisso simples: no dia, retome com pergunta direta e ofereça ajuda para finalizar. Se o motivo for banco/cartão, peça para avisar assim que finalizar.\n\nMensagens exemplo: \"Perfeito. Então ficou pra quarta, certo? Posso te chamar na quarta e em qual horário fica melhor?\" \"Combinado, te chamo no horário e te ajudo a finalizar rapidinho.\" \"Assim que finalizar, me avisa aqui.\"\n\nO que NÃO fazer: não pressionar com ameaça de perder vaga de forma agressiva; não criar condição especial; não deixar sem próximo passo (sempre sair com data/horário e permissão de contato)."
  },
  {
    "objecao": "adiamento",
    "titulo": "Adiamento por indecisão/validação (analisar opções, falar com pais, medo do edital, forma de pagamento) + risco/clareza",
    "gatilhos": "vou pensar e te retorno / preciso falar com minha mãe / conversando com meus pais / gostaria de analisar direitinho / me dá um tempinho pra ver qual opção / medo de não abrir o edital / estou analisando se vai ser no cartão ou boleto / até que horas posso dar a resposta / vou pensar / vou pensar e te falo / preciso falar com meu marido / vou ver com minha esposa / vou conversar com minha família antes",
    "conteudo": "Instrução: descubra o que falta para decidir (dúvida, comparação de planos, forma de pagamento, receio de timing do edital). Traga clareza sobre os dois planos que você apresentou (o recomendado e o Semestral) e sobre como é o começo. Combine um prazo de retorno e peça para avisar assim que decidir. Quando fizer sentido, reduza risco lembrando da garantia de 7 dias (sem exagerar).\n\nMensagens exemplo: \"Entendi. O que falta pra você decidir: escolher o plano, alinhar com seus pais ou é a forma de pagamento?\" \"Ficou entre os dois planos? Me fala o que pesa que eu te ajudo a decidir.\" \"Pode decidir com calma. Me avisa quando decidir. E você tem 7 dias de garantia.\"\n\nO que NÃO fazer: não inventar ‘última vaga’ ou escassez não confirmada; não empurrar decisão sem entender a trava; não prometer edital/data de prova."
  },
  {
    "objecao": "duvida_produto",
    "titulo": "Como funciona a mentoria (o que está incluso)",
    "gatilhos": "como funciona a mentoria? / me explica um resumo de como funciona / o que vocês oferecem? / na plataforma tem todas as matérias? / no aplicativo tem aula? como funciona? / esse material do estratégia é o quê? / tem simulados? banco de questões? / tem acompanhamento ou é só aula jogada?",
    "conteudo": "Explique de forma objetiva que a mentoria não é só um cursinho: é método + planejamento/cronograma + acompanhamento. Deixe claro o que o aluno recebe no dia a dia (metas, o que estudar, quando revisar e fazer questões), quais canais de suporte existem (encontros ao vivo, WhatsApp, plataforma) e quais recursos aparecem nas respostas (simulados, relatórios mensais, banco de questões). Se o lead perguntar de “material do Estratégia”, esclareça que é a assinatura/plataforma com videoaulas, PDFs e questões (quando aplicável ao plano). Se o lead estiver perdido/inseguro, valide a dor e conecte com o benefício de direcionamento por prioridade (evitar estudar o que não cai). Feche perguntando qual concurso/cargo e nível para ajustar a explicação.\nExemplos de mensagens:\n\"A mentoria é pra você não estudar no escuro: o Walker monta seu cronograma por prioridade (o que estudar, revisar e quais questões fazer por dia) e você acompanha tudo na plataforma.\"\n\"Além do cronograma, você tem encontros ao vivo, suporte no WhatsApp e simulados/relatórios pra ajustar o estudo conforme seu desempenho.\"\n\"Sobre o material do Estratégia: é a assinatura com videoaulas, PDFs e questões; a mentoria entra com o método e o direcionamento do que fazer primeiro.\"\nO que NÃO fazer: não prometer correção direta de discursiva quando a resposta real diz que não há correção direta; não inventar recursos que não foram citados (ex.: ‘tutor 24h’, ‘aulas diárias’)."
  },
  {
    "objecao": "duvida_produto",
    "titulo": "Personalização e direcionamento (cronograma, específicas, replanejamento)",
    "gatilhos": "o cronograma é individual ou geral? / é personalizado pra minha formação? / vocês direcionam matérias específicas (engenharia, farmácia)? / se eu estiver errando muito vocês ajustam? / pós-edital vocês replanejam? / se o concurso for antes do fim do plano eu continuo com acesso? / posso adaptar o período excedente pra outro concurso?",
    "conteudo": "Confirme que o cronograma é personalizado por edital, banca, cargo e nível, incluindo matérias específicas e generalistas. Explique que o acompanhamento permite ajustes (ex.: mensalmente via relatório/avaliação) e que no pós-edital são feitas adequações. Se a dúvida for sobre prova antes do fim do plano, responda que mantém acesso e pode solicitar replanejamento para outro concurso. Termine pedindo qual concurso/cargo e data provável para orientar o melhor caminho.\nExemplos de mensagens:\n\"Seu cronograma é individual: eu monto por prioridade com base no edital, banca e no seu nível, incluindo as específicas do seu cargo.\"\n\"Se em alguma matéria você estiver com mais dificuldade, a gente ajusta o planejamento conforme seu desempenho e os relatórios.\"\n\"Se a prova sair antes do fim do seu plano, você continua com acesso e pode pedir replanejamento pra outro concurso.\"\nO que NÃO fazer: não garantir aprovação; não dizer que o replanejamento é automático sem solicitação quando as respostas indicam que pode solicitar ao suporte; não inventar ‘mentoria 100% individual diária’ se não foi citado."
  },
  {
    "objecao": "duvida_produto",
    "titulo": "Dúvidas operacionais (NF, acesso, celular, renovação, histórico, áudio)",
    "gatilhos": "vocês emitem NF? / não tem renovação automática? / consigo acessar pelo celular? / meu histórico fica salvo? / o primeiro pagamento é quando? / posso mandar um áudio? / é esse o link ainda? / se eu pagar recorrente meu histórico permanece?",
    "conteudo": "Responda direto e sem rodeios a dúvida operacional. Confirme emissão de NF quando perguntarem. Esclareça as regras de acesso: vale pelo período do plano, sem renovação automática, e dá pra acessar pelo celular. Se o lead quiser mandar áudio, autorize e tranquilize. Se perguntarem sobre link, confirme e ofereça ajuda para concluir. Evite alongar com explicações de produto se a pergunta é só operacional; depois de responder, faça uma pergunta simples para avançar (ex.: ‘quer que eu te ajude a finalizar?’).\nExemplos de mensagens:\n\"Sim, emitimos NF.\"\n\"Não tem renovação automática: você paga agora e fica com acesso pelo período do plano, sem surpresas.\"\n\"Pode mandar o áudio sim, fica tranquilo que eu te ajudo a esclarecer tudo pra você fechar com segurança.\"\nO que NÃO fazer: não criar condições especiais; não pressionar com escassez; não mudar de assunto antes de responder objetivamente."
  },
  {
    "objecao": "tempo",
    "titulo": "Rotina corrida: pouco tempo pra estudar/conciliar",
    "gatilhos": "Hoje eu tenho uma carga horária limitada para estudar / Não sei se dá pra conciliar / Mas trabalho 58h semanais e estudo para a residência / vou viajar uns 20 dias mês que vem e talvez não consiga estudar como gostaria / Vc acha q dá ? / Quantas horas por dia seria ideal? / Sempre vou vender minha hora / pq a prova já é em janeiro",
    "conteudo": "Instrução para o Walker: valide a rotina puxada e tire o peso de “precisar de muitas horas”. Reforce que o diferencial é método + acompanhamento para fazer cada hora render, e que o cronograma é adaptado à vida real (plantão, viagem, residência). Se o lead pedir, dê uma referência simples de horas/dia (2 a 4h ou 2 a 3h para rotina intensa) e traga a ideia de replanejamento quando a rotina mudar. Feche com uma pergunta de compromisso: quantas horas reais ele consegue e qual concurso/objetivo, para você ajustar o plano.\nExemplos de mensagens (máx. 3): \"Entendo total sua rotina. A ideia da mentoria é justamente fazer cada hora render mais, com um plano bem focado e acompanhamento.\" / \"Mesmo com pouco tempo dá pra avançar, desde que esteja organizado. Em geral o pessoal consegue manter 2 a 3h por dia quando a rotina é puxada, e a gente ajusta pra sua realidade.\" / \"Se você viajar ou tiver plantão, a gente replaneja as metas. Me diz: quantas horas reais você consegue na semana pra eu te orientar no melhor caminho?\"\nO que NÃO fazer: não prometer aprovação; não minimizar a rotina do lead; não empurrar “estude X horas fixas” sem adaptar; não inventar datas de prova/edital."
  },
  {
    "objecao": "tempo",
    "titulo": "Prazo e planejamento: dá tempo? começo do zero? pré vs pós-edital",
    "gatilhos": "Será que não seria pouco tempo? Eu começaria do zero os estudos / não será de aprovação, mas eu quero estar no caminho de uma aprovação / Eu ainda estou na graduação e me formo no final de 2028 / A mentoria ajuda a montar um planejamento a longo prazo ou é mais focada em pós edital? / Ja e sabido quanto tempo baseado na saida da banca para quanto tempo e a prova? Media / Vcs acham que a prova da PCRJ vai ser quando / To na duvida entre o semestral e anual por conta do tempo / Se o edital sair em dezembro e prova em fevereiro março",
    "conteudo": "Instrução para o Walker: primeiro, alinhe expectativa de tempo: explique que a mentoria serve desde o pré-edital (base e constância) e que, quando sair edital, você ajusta o plano. Se o lead está do zero, tranquilize com cronograma e foco no que mais cai. Quando perguntarem “média de tempo”, responda que varia, mas traga a referência de 5 a 6 meses como média razoável e reforce a necessidade de estratégia e priorização. Se houver especulação de datas, não cravar: oriente a não se apegar a especulações e começar antes para chegar à frente. Feche perguntando qual concurso-alvo e janela de tempo que o lead tem.\nExemplos de mensagens (máx. 3): \"A mentoria não é só pós-edital. A gente monta um planejamento desde o pré-edital e, quando sair o edital, eu ajusto tudo pra você.\" / \"Mesmo começando do zero, dá pra organizar com cronograma e priorização do que mais cai. O importante é começar com estratégia.\" / \"Sobre prazo, varia, mas uma média razoável é 5 a 6 meses. Me diz qual concurso você quer focar agora pra eu te orientar no melhor caminho.\"\nO que NÃO fazer: não prometer data de edital/prova; não garantir aprovação; não dizer que “sempre dá tempo” sem entender o cenário do lead."
  },
  {
    "objecao": "tempo",
    "titulo": "Duração/acesso e início: quando começa, quanto tempo dura, renovação/upgrade",
    "gatilhos": "E terei acesso por qnto tempo? / Deixa eu te perguntar: quanto tempo dura a mentoria? Até a data do concurso? / O acesso é somente durante esses doze meses? / Espera, a mentoria era só de 6 meses? Eu achei q era de 1 ano / se eu começar com o de seis meses, depois teria a possibilidade de fazer um upgrade? / A mentoria inicia quando eu pagar o primeiro boleto? / meu cronograma fica pronto qdo? quanto tempo demora pra começar? / O q vcs tem feito qnd a mentoria do aluno termina e ainda faltam 2 ou 3 meses pra prova?",
    "conteudo": "Instrução para o Walker: esclareça objetivamente a regra de duração (conforme plano escolhido) e o marco de início (a partir da matrícula/pagamento confirmado). Quando perguntarem sobre “até a prova”, alinhe que é por período contratado, mas existe possibilidade de renovação se a prova ficar depois do término. Se o lead estiver em dúvida entre durações, faça uma pergunta de contexto (qual concurso e horizonte) e recomende o tempo que dá mais segurança, sem falar de preço. Se a prova sair antes do fim do plano, o aluno mantém o acesso e pode pedir replanejamento para outro concurso.\nExemplos de mensagens (máx. 3): \"O acesso e o acompanhamento duram pelo período do plano que você escolher. E começa a contar a partir da sua matrícula.\" / \"Se a prova ficar depois do término, dá pra renovar por mais tempo. A ideia é você não ficar sem acompanhamento na reta final.\" / \"Se a prova sair antes do fim do plano, você continua com acesso e pode pedir replanejamento pra outro concurso.\"\nO que NÃO fazer: não inventar flexibilidade que não existe (ex.: alterar datas quando não há opção); não usar escassez/urgência inventada; não prometer liberação sem confirmação quando o processo exige matrícula/pagamento."
  },
  {
    "objecao": "engajamento",
    "titulo": "Desânimo / não consegue manter constância",
    "gatilhos": "não consigo manter os estudos / fico com vontade mas não estudo / me trava muito / não consigo estudar todo dia / acabei desanimando e não peguei mais pra estudar / Tentando voltar / Parei e não consegui mais voltar / Não sei pq não consigo voltar",
    "conteudo": "Valide a dificuldade e normalize (é comum). Mostre que o problema costuma ser direção/método e não esforço. Em seguida, investigue com uma pergunta para diagnosticar (o que está travando, há quanto tempo estuda, rotina). Se a rotina mudou, sugira retomada gradual com carga menor para recuperar ritmo. Reforce que dá para retomar e recuperar.\n\nMensagens exemplo:\n\"Isso é muito comum em quem estuda pra concurso. Não é falta de esforço, quase sempre é falta de direção e método. Você já estuda há quanto tempo?\"\n\"Ah, entendi. Cada dia sem estudar pesa muito na preparação depois, mas dá pra retomar e recuperar o ritmo.\"\n\"O que você acha que falta hoje pra conseguir voltar aos estudos?\"\n\nO que NÃO fazer: não culpar o lead; não dar sermão; não prometer aprovação; não empurrar solução sem antes entender o travamento."
  },
  {
    "objecao": "engajamento",
    "titulo": "Falta de direção/organização (não sabe por onde começar, cronograma, revisão, foco)",
    "gatilhos": "não sei por onde começar / não consigo montar um roteiro e seguir / falta um cronograma / falta organização / sempre acho que tá faltando algo / não consigo finalizar o que iniciei / nunca consegui fazer revisão / só via as videoaulas / falta direcionamento sobre aonde focar",
    "conteudo": "Confirme a dor e normalize (é comum e não é falta de esforço). Seja transparente sobre o que é a mentoria (não é cursinho; o diferencial é acompanhamento e método). Conecte a dor do lead com o que a mentoria organiza: cronograma com estudos, revisões e questões, metas e acompanhamento. Termine com uma pergunta de confirmação para avançar (se ele sente isso na hora de estudar / se é o momento de começar).\n\nMensagens exemplo:\n\"Essa sensação de não saber por onde começar é o que mais trava quem estuda sozinho, e é o primeiro ponto que a gente organiza junto. Você também sente isso na hora de estudar?\"\n\"Deixa eu ser transparente: a mentoria não é um cursinho. O que muda o jogo é acompanhamento e método.\"\n\"Na mentoria, o Walker monta seu cronograma com estudos, revisões e questões diárias e acompanha de perto. Você sente que falta isso pra você também?\"\n\nO que NÃO fazer: não vender como se fosse só material/aulas; não exagerar promessas; não usar escassez inventada; não ignorar a dor e ir direto para fechamento."
  },
  {
    "objecao": "edital_concurso",
    "titulo": "Quando sai o edital/prova e se sair antes?",
    "gatilhos": "Vocês tem perspectiva do PCDF? / Vcs tem alguma informaçao de qnd deve ser o concurso pcdf? / Você acredita que o edital da PCDF ainda saia esse ano? / Quando sai o edital? / E se o edital sair antes? / E se sair antes reprograma? / temos previsão de quando será a prova? / Entre o edital e a prova, quantos meses terei para estudar?",
    "conteudo": "Explique o que dá para afirmar (previsão/andamento e que pode variar), sem cravar data. Reforce que, quando o edital sair, o plano/cronograma e o material são ajustados para o pós-edital e para o edital específico, então não há risco de “perder” o direcionamento. Use isso para puxar o lead para a decisão de começar antes, destacando que o intervalo edital-prova costuma ser curto. Se o lead perguntar de prova, dê a noção geral (2 a 3 meses em média) e ressalte variação.\n\nMensagens exemplo:\n\"Data de edital ninguém consegue cravar. O que eu te garanto é que, assim que sair, a gente ajusta todo o plano pro pós-edital e foca no que o edital pedir.\"\n\"Em geral, do edital até a prova costuma dar uns 2 a 3 meses, então quem começa antes chega com base pronta quando publicar.\"\n\"Mesmo que demore um pouco, a mentoria já te deixa preparado e, quando sair, a gente replaneja tudo em cima do edital.\"\n\nO que NÃO fazer: não prometer data certa de edital/prova; não inventar informação de bastidor; não usar pressão/escassez como argumento principal."
  },
  {
    "objecao": "edital_concurso",
    "titulo": "Conteúdo/cronograma vai bater com o edital e com minha área?",
    "gatilhos": "Em relação ao material específico para a PCIES / após edital teria algum aprimoramento do edital? / Meu medo é eu comprar o curso do pci e não ter nada sobre isso no edital da pcdf / Só uma dúvida o cronograma que é passado para estudo é voltado para os conteúdos de perito farmacêutico? / Pq tem a parte das questões específicas / De qualquer forma precisamos esperar o edital / Como posso verificar? / Existe uma possibilidade",
    "conteudo": "Valide a preocupação e responda com segurança que o material e o plano são ajustados assim que o edital sai, para o edital específico e para a formação/cargo do aluno. Se a dúvida for sobre “precisar esperar o edital” por causa de enquadramento/equiparação, oriente a checar com o conselho regional do curso para antecipar a confirmação, e em paralelo reforce que não é recomendado esperar edital para começar a base. Se o lead tiver medo de não cair no edital, explique que a mentoria direciona o foco conforme o edital publicado.\n\nMensagens exemplo:\n\"Sim. Assim que sai o edital, a gente faz todas as alterações necessárias no material e ajusta o plano em cima do edital específico.\"\n\"O cronograma é personalizado conforme sua formação e o edital do concurso, pra você estudar exatamente o que precisa pro seu cargo.\"\n\"Se a sua dúvida é enquadramento, dá pra ver com o conselho regional do seu curso sobre equiparação e não ficar refém de esperar o edital pra confirmar.\"\n\nO que NÃO fazer: não garantir que uma área vai estar no edital sem confirmação; não dizer para “esperar o edital” como única saída quando existe ação prática (conselho/equiparação); não prometer aprovação."
  },
  {
    "objecao": "edital_concurso",
    "titulo": "Vai ter vaga/mentoria para minha graduação (legista, economia, etc.)?",
    "gatilhos": "Só que minha dúvida é se irá abrir pra legista em farmácia / Ainda não foi definido a quantidade né / Terá mentoria para legista ? / Provavelmente que as duas será no mesmo dia né / o que me preocupa é a abertura da vaga para economia ou não / Você tem alguma perspectiva em cima disso? / Vai abrir para todas essas 13 graduações entao? / Já saíram as áreas que terão vagas?",
    "conteudo": "Primeiro, faça uma pergunta de qual estado/concurso para não responder no genérico. Depois, traga a informação objetiva que existe (áreas/vagas quando já divulgado) e, se aplicável, esclareça que o candidato precisa optar entre cargos (quando for o caso). Em seguida, conecte com o valor da mentoria: o problema comum é não saber o que priorizar e como revisar, e a mentoria resolve com direcionamento. Se o lead estiver inseguro porque a área pode não abrir, acolha e mantenha a conversa para entender se ele já está estudando e qual plano faz sentido.\n\nMensagens exemplo:\n\"Qual estado/concurso você tá mirando? Aí eu te confirmo certinho se tem vaga pra sua formação.\"\n\"Se o edital ainda não saiu, ninguém consegue cravar quais áreas vão abrir. Começar antes é o que te deixa pronto quando sair.\"\n\"O grande problema de quem começa é não saber o que priorizar e quando revisar; com a mentoria você não fica tentando estudar tudo sem evoluir.\"\n\nO que NÃO fazer: não inventar número de vagas/áreas sem base; não afirmar que “vai abrir” para uma graduação se ainda não saiu; não desviar para preço antes de esclarecer a elegibilidade."
  },
  {
    "objecao": "material_curso",
    "titulo": "Tem material incluso? O que é esse material (Estratégia) e o que vem no plano",
    "gatilhos": "O material seria o que / o que seria esse material do estratégia mesmo? / vcs tem material para estudar tb? / Vocês tem material também? / N tem material de estudo né? / sem material tem acesso a plataforma toda né? / Esse plano inclui o material do Estratégia? / vocês só orienta o estudo ou tem material também?",
    "conteudo": "Explique com clareza o que é “material” na mentoria: a mentoria é principalmente direcionamento (planejamento, metas, acompanhamento, encontros, simulados/questões/recursos da plataforma) e, dependendo da modalidade, pode incluir a assinatura premium do Estratégia como fonte de estudo. Confirme qual modalidade o lead quer (com ou sem Estratégia) e tranquilize sobre acesso à plataforma. Se o lead perguntar se “tem material”, responda sem prometer que é um cursinho completo. Finalize com uma pergunta simples de próximo passo (qual plano faz mais sentido/posso te orientar na escolha).\nExemplos de mensagens:\n\"Material é a sua fonte de estudos. Na mentoria você tem todo o direcionamento e, na modalidade com material, vai junto a assinatura premium do Estratégia pra você usar durante o período.\"\n\"A mentoria não é um cursinho tradicional: a gente te entrega planejamento, metas, acompanhamento e direcionamento. O material (quando incluso) é o Estratégia; se for a modalidade sem material, você segue com o que já tem.\"\n\"Me diz: você prefere fazer com o Estratégia incluso ou usar seu material? Aí eu te confirmo a modalidade certinha.\"\nO que NÃO fazer: não inventar que “tem todo material de todas as áreas” quando a resposta real diz que não é preparatório completo; não prometer aprovação; não usar escassez/urgência inventada; não falar de cupom/desconto/link."
  },
  {
    "objecao": "material_curso",
    "titulo": "Já tenho material (Estratégia/Gran/livros/anotações) ou quero usar o que tenho",
    "gatilhos": "Eu já tenho o material do Estratégia / Comprei no final do ano passado / Eu tenho o Gran cursos / estou estudando por livros / uso anotações antigas / ou você acredita que é possível fazer com os materiais que tenho a disposição / Deixa eu te perguntar, quanto ao material, é adaptado ao que tenho, correto? / Se eu já tiver material, dá pra seguir com ele?",
    "conteudo": "Valide que dá para fazer usando material próprio e reforce que o diferencial é o cronograma e o direcionamento (o que estudar, quando e com prioridade). Se o lead estiver em livros/anotações, explique que um material mais objetivo otimiza tempo e revisão, porque o concurso exige volume e foco nos pontos mais cobrados. Se o lead já tem Estratégia, direcione para a modalidade sem material (sem entrar em preço/link) e avance perguntando se ele quer seguir com o que já tem.\nExemplos de mensagens:\n\"Pode usar seu material normalmente. Você só vai seguir o cronograma da mentoria com prioridade e metas, pra estudar com foco no que mais cai.\"\n\"Se você já tem o Estratégia, faz sentido seguir na modalidade sem material e aproveitar o que você já comprou.\"\n\"Por livros dá pra estudar, mas costuma tomar muito tempo. Um material mais objetivo ajuda a cobrir mais assuntos e revisar os pontos-chave do concurso.\"\nO que NÃO fazer: não desqualificar o material do lead de forma agressiva; não dizer que “sem Estratégia não dá”; não prometer que a mentoria substitui qualquer material em todos os casos."
  },
  {
    "objecao": "material_curso",
    "titulo": "Material do Estratégia é denso/confuso ou dificuldade de achar material específico (falta de direcionamento)",
    "gatilhos": "Eu acho um conteúdo muito denso / lia pdfs mil páginas e sem foco / Vocês fazem o cronograma com leitura de todos os pdfs? / mas você acha que eu vou conseguir ser eficiente sem ele no primeiro semestre? / Tenho dificuldade em buscar material específico pra estudar / Falta de direcionamento / material base pra conhecimentos específicos (TI) / Meu foco é perito biomédico",
    "conteudo": "Reconheça a dor (densidade/falta de foco/dificuldade de achar material) e explique que a mentoria resolve isso com priorização: não é para ler tudo, é para estudar por ordem de importância e com direcionamento. Mantenha a resposta no que a mentoria entrega: planejamento, metas, acompanhamento, encontros e suporte.\nExemplos de mensagens:\n\"Faz sentido: o Estratégia é bem denso mesmo. Na mentoria você não vai sair lendo tudo; o cronograma vem por prioridade, focando no que mais pontua e no que mais cai.\"\n\"Se sua dificuldade é achar material específico, a mentoria te dá o direcionamento e o planejamento pro seu cargo/área pra você não ficar perdido.\"\n\"Com o plano da mentoria você sabe o que estudar em cada material, sem ficar perdido entre PDF e videoaula.\"\nO que NÃO fazer: não prometer que existe “material base pronto” para toda área específica quando as respostas mostram que o foco é método/direcionamento; não afirmar que nunca será necessário material externo; não inventar garantias de resultado."
  },
  {
    "objecao": "formacao_area",
    "titulo": "Ainda não formado(a): quer começar cedo e planejar até o edital",
    "gatilhos": "Eu ainda estou na graduação e me formo no final de 2028 / A mentoria também ajuda a montar um planejamento a longo prazo? / ou a preparação é mais focada em pós edital? / Estou no último semestre da faculdade / Ainda não sou formada, termino esse ano / Quero começar a estudar para concurso / Tenho sentido falta de estudar algo / sensação de não saber por onde começar",
    "conteudo": "Explique que a mentoria organiza o estudo desde o pré-edital (planejamento de longo prazo) e que, quando o edital sair, o Walker ajusta o plano. Valide a decisão de começar antes e foque no benefício de ter direção (o que estudar, quando revisar, questões). Se o lead demonstrar travamento, ofereça mostrar rapidamente como funciona por dentro (vídeo/explicação), sem empurrar. Exemplos de mensagens: \"Ajuda sim: a mentoria organiza seu planejamento desde o pré-edital e, quando sair o edital, o Walker ajusta tudo pra sua realidade.\" \"Começar ainda na faculdade é uma ótima ideia, porque você já vai construindo base e método, sem ficar perdido(a) no que priorizar e quando revisar.\" \"Se você quiser, eu te explico rapidinho como funciona por dentro e como a gente monta esse plano de longo prazo.\" O que NÃO fazer: não prometer aprovação; não dizer que é só pós-edital; não inventar prazos/escassez."
  },
  {
    "objecao": "formacao_area",
    "titulo": "Conteúdo/cronograma por área: quer saber se é específico para a formação e edital",
    "gatilhos": "A mentoria vai pegar os conteúdos das matérias específicas da minha área da graduação? / Eu sou Biomédica / a mentoria será organizada de acordo com a minha área específicas que é a psicologia? / gostaria de mais informções sobre mentoria para o concurso PC MA Engenharia Civil / mas específico para Engenharia Civil? / Mas esse curso atende ao cargo de Biomedicina? / Posso adaptá-lo para o concurso de perícia do ES para Biomedicina? / Sou farmacêutica",
    "conteudo": "Confirme que a mentoria é personalizada e que o plano é montado com base no edital e na banca do concurso-alvo, adaptado à formação do aluno. Reforce o resultado prático do plano (saber o que estudar, revisar e quais questões fazer) e que o foco é direcionar para o que é mais relevante para aquela área dentro do concurso. Se o lead perguntar de “base/conteúdo”, explique o que está incluído na mentoria conforme a resposta real (ex.: para médicos, inclui assinatura do Estratégia e itens citados). Exemplos de mensagens: \"Sim. A mentoria é personalizada: o Walker monta seu cronograma com base no edital e na banca do concurso que você mira, adaptando pra sua formação.\" \"A ideia é você estudar de forma direcionada: o que estudar, quando revisar e quais questões fazer, priorizando o que costuma ser cobrado pra sua área.\" \"No seu caso, me diz qual concurso/estado você está mirando pra eu te explicar como a gente adapta o plano pra esse edital.\" O que NÃO fazer: não afirmar conteúdos específicos que não estejam no edital; não prometer que ‘cai com certeza’; não inventar materiais inclusos fora do que foi dito (só mencionar inclusão do Estratégia no contexto ‘mentoria para médicos’, como nas respostas reais)."
  },
  {
    "objecao": "formacao_area",
    "titulo": "Aceitação da formação (tecnólogo/tempo de curso): dúvida se pode tomar posse",
    "gatilhos": "sou formado em Análise e Desenvolvimento de Sistemas (tecnólogo), é normalmente aceito? / Qual foi a duração do seu curso? / 2 anos / normalmente é aceito na área de TI / mas não confirmei para cargo de perito",
    "conteudo": "Faça triagem objetiva pedindo a duração do curso e contextualize que a aceitação pode variar por edital e compatibilidade de disciplinas. Oriente o lead a verificar a situação (conselho/edital) e mantenha a conversa no caminho de confirmar elegibilidade. Exemplos de mensagens: \"Qual foi a duração do seu curso? Isso ajuda a entender se sua formação costuma ser aceita pro cargo na área de TI.\" \"Em muitos editais, pode existir exigência de curso mais longo, mas também depende da compatibilidade das disciplinas e do que o edital pede.\" \"Isso muda de edital pra edital, então vale checar no edital ou no órgão quando sair pra confirmar sua situação.\" O que NÃO fazer: não cravar que ‘é aceito’ sem ver edital; não dar parecer jurídico definitivo; não prometer que a mentoria resolve requisito de formação."
  },
  {
    "objecao": "concorrencia",
    "titulo": "Comparando com outros cursos/preparatórios",
    "gatilhos": "Eu já assino o Gran concursos, isso tem alguma diferença? / Quase nesse valor eu tenho outra proposta pra 1 ano de outro preparatorio / Eu tenho uma outra proposta da Aline Lyra / inclusive também tenha acesso a um curso do Rodolfo Souza / existem muitos cursos dizendo que são os que mais aprovam / Tem aulas, pdfs… / Quais os valores e como funciona",
    "conteudo": "Instrução pro Walker: validar que o lead está comparando e trazer a diferença central que aparece nas respostas vencedoras: mentoria = direcionamento + acompanhamento (não é só conteúdo). Mostrar que a mentoria aproveita o material que ele já tem e evita desperdício de tempo com assuntos de baixa probabilidade. Se o lead pedir para “igualar” concorrente, não entrar em briga de preço; reposicionar para valor (individual, acompanhamento, método) e, se fizer sentido, oferecer alternativa de começar mais leve (plano menor) apenas quando isso estiver disponível na oferta. Pode citar garantia de 7 dias quando o lead estiver inseguro para decidir.\nExemplos de mensagens (1 a 3):\n\"Entendo total você comparar. A diferença é que aqui não é só mais um curso: é acompanhamento e direcionamento do seu estudo.\"\n\"Mesmo que você já tenha Gran/curso X, a mentoria entra pra te dizer o que priorizar e o que não vale gastar energia, focando no que tem mais probabilidade de cair.\"\n\"Se fizer sentido, você ainda tem 7 dias pra testar e ver se o acompanhamento te ajuda de verdade.\"\nO que NÃO fazer: não prometer aprovação, não inventar escassez, não atacar concorrentes, não tentar “cobrir” proposta com desconto/cupom."
  }
];
